In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
print(a,type(a),a.shape,sep='\n')

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
b=np.array([[1],[2],[3],[4],[5]])
print(b,b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]] (5, 1)


In [5]:
c=np.array([[1,2,3],[4,6,6]])
print(c.shape)
print(c[1][1])

(2, 3)
6


In [6]:
#zeroes,ones,custom
a=np.zeros((3,3))
print(a)
b=np.ones((2,3))
print(b)
c=np.full((3,3),2)
print(c)
#identity matrix :-sq mat
d=np.eye(4)
print(d)
#random
randomMatrix=np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.39682494 0.58253755 0.02258201]
 [0.96819321 0.26605472 0.15570537]]


In [7]:
print(randomMatrix[0:2,1:2])

[[0.58253755]
 [0.26605472]]


In [8]:
randomMatrix[1,1:]=1
print(randomMatrix)

[[0.39682494 0.58253755 0.02258201]
 [0.96819321 1.         1.        ]]


In [9]:
##set some rows and cols Slicing
z=np.zeros((3,3))
print(z)
z[1,:]=1
z[:,-1]=8
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 8.]
 [1. 1. 8.]
 [0. 0. 8.]]


In [10]:
#DataTypes
print(z.dtype)
z=np.zeros((3,3),dtype=np.int64)
print(z.dtype)

float64
int64


In [11]:
#mathematical opn

x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x+y)#np.add
print(x*y)#np.subtract
print(x/y)
print(np.sqrt(x))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [12]:
#matmul / dot product
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [13]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(np.dot(a,b))#scaler

30


In [14]:
print(sum(a))
print(np.sum(a))


10
10


In [15]:
x
print(np.sum(x))
print(np.sum(x,axis=1))
print(np.sum(x,axis=0))

10
[3 7]
[4 6]


In [16]:
#stack
print(a,b)
b=b**2
print(b)

[1 2 3 4] [1 2 3 4]
[ 1  4  9 16]


In [17]:
print(np.stack((a,b),axis=0))
np.stack((a,b),axis=1)

[[ 1  2  3  4]
 [ 1  4  9 16]]


array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [18]:
#reshape
a=np.stack((a,b),axis=0)
a=a.reshape((4,2))
print(a)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [19]:
a.reshape((1,8))

array([[ 1,  2,  3,  4,  1,  4,  9, 16]])

In [20]:
a.reshape((2,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 1,  4],
        [ 9, 16]]])

**Random**

In [21]:
a=np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [22]:
import random

In [23]:
np.random.shuffle(a)
print(a)

[12  7 10  5 13  6 14 11  8  9]


In [24]:
#return values from standard normal distribution
a=np.random.randn(2,3)
print(a)

[[-0.37396255 -0.40887412  0.92999198]
 [-0.0695404  -0.10444648 -1.53399986]]


In [25]:
a=np.random.randint(5,10,3)
print(a)

[5 5 8]


In [26]:
element=np.random.choice([1,4,3,2,7,11])
print(element)

7


In [27]:
np.random.seed(11)#replication
np.random.randint(0,10)

9

**Mean,median,std**

In [28]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.min(a))
print(np.min(a,axis=0))
print(np.argmin(a,axis=1))
print(np.argmax(a,axis=1))

[[1 2 3 4]
 [5 6 7 8]]
1
[1 2 3 4]
[0 0]
[3 3]


In [29]:
a=np.array([1,2,3,4,5])
mean=np.sum(a)/5
print(mean,np.mean(a))
a=np.array([[1,2,3,4],[5,6,7,8]])
print(np.mean(a,axis=0),np.mean(a,axis=1))

3.0 3.0
[3. 4. 5. 6.] [2.5 6.5]


In [30]:
c=np.array([1,5,4,2,0])
print(np.mean(c),np.median(c))
wts=np.array([1,2,3,4,5])
print(np.average(c,weights=wts))

#standard deviation
mystd=np.sqrt(np.mean(abs(c-np.mean(c))**2))
print(mystd,np.std(c))

print(mystd**2)#variance

2.4 2.0
2.066666666666667
1.854723699099141 1.854723699099141
3.440000000000001
